
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HASIB
 */
public class tictoc extends javax.swing.JFrame {
      String Startgame = "x";
      int xcount = 0;
      int ocount = 0;
    /**
     * Creates new form tictoc
     */
    public tictoc() {
        initComponents();
        setSize(1000,600);
        setLocationRelativeTo(null);
        
    }
    void gamescore(){
     jLabel4.setText(String.valueOf(xcount));
     jLabel5.setText(String.valueOf(ocount));
    }
    void choose_player(){
        if(Startgame.equalsIgnoreCase("x")){
            Startgame = "0";
        }else{
            Startgame = "x";
        }
    }
    void winningame(){
        String b1 = jButton1.getText();
        String b2 = jButton2.getText();
        String b3 = jButton3.getText();
        
        String b4 = jButton4.getText();
        String b5 = jButton5.getText();
        String b6 = jButton6.getText();
        
        String b7 = jButton7.getText();
        String b8 = jButton8.getText();
        String b9 = jButton9.getText();
        if(b1=="x" && b2=="x" && b3=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b4=="x" && b5=="x" && b6=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b7=="x" && b8=="x" && b9=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b1=="x" && b4=="x" && b7=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b2=="x" && b5=="x" && b8=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b3=="x" && b6=="x" && b9=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b1=="x" && b5=="x" && b9=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b3=="x" && b5=="x" && b7=="x"){
          JOptionPane.showMessageDialog(this,"Player X is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          xcount++;
          gamescore();
        }
        if(b1=="0" && b2=="0" && b3=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b4=="0" && b5=="0" && b6=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b7=="0" && b8=="0" && b9=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b1=="0" && b4=="0" && b7=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b2=="0" && b5=="0" && b8=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b3=="0" && b6=="0" && b9=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b1=="0" && b5=="0" && b9=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
        if(b3=="0" && b5=="0" && b7=="0"){
          JOptionPane.showMessageDialog(this,"Player 0 is win","Tictoc",JOptionPane.INFORMATION_MESSAGE);
          ocount++;
          gamescore();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tictoc");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PlayerX:");
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Player0:");
        jPanel10.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Exit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton11, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel16);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"if u want to exit","Tictoc",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton1.setForeground(Color.red);
        }else{
            jButton1.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton2.setForeground(Color.red);
        }else{
            jButton2.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton3.setForeground(Color.red);
        }else{
            jButton3.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton4.setForeground(Color.red);
        }else{
            jButton4.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton5.setForeground(Color.red);
        }else{
            jButton5.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton6.setForeground(Color.red);
        }else{
            jButton6.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton7.setForeground(Color.red);
        }else{
            jButton7.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton8.setForeground(Color.red);
        }else{
            jButton8.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setText(Startgame);
        if(Startgame.equalsIgnoreCase("x")){
            jButton9.setForeground(Color.red);
        }else{
            jButton9.setForeground(Color.blue);
        }
        choose_player();
        winningame();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         jButton1.setText(null);
         jButton2.setText(null);
         jButton3.setText(null);
        
         jButton4.setText(null);
         jButton5.setText(null);
         jButton6.setText(null);
        
         jButton7.setText(null);
         jButton8.setText(null);
         jButton9.setText(null);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
